language: php

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run --rm mappics composer install
  - docker-compose run --rm mappics bin/console cache:clear --env=test
  - docker-compose run --rm mappics bin/console doctrine:migrations:migrate --env=test --no-interaction

script:
  - mkdir -p build/logs
  - docker-compose run --rm mappics bin/phpunit --coverage-clover=coverage.xml
  - docker-compose run --rm mappics vendor/bin/infection --min-msi=70 --threads=4

after_success:
  - bash <(curl -s https://codecov.io/bash)