monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 30
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
            verbosity_levels:
                VERBOSITY_NORMAL: CRITICAL
